# Generated by Django 4.2.23 on 2025-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_id_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id_proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
