# Generated by Django 4.2.23 on 2025-10-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_customer_id_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('temple', 'Main Temple'), ('prayers', 'Morning Prayers'), ('cultural', 'Cultural Programs'), ('accommodation', 'Accommodation'), ('dining', 'Dining Hall'), ('gardens', 'Temple Gardens'), ('festivals', 'Festivals'), ('ceremonies', 'Ceremonies')], max_length=50)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
