# Generated by Django 4.2.23 on 2025-10-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('श्री', 'श्री'), ('श्रीमती', 'श्रीमती'), ('श्रीमान', 'श्रीमान'), ('स्वर्गीय श्री', 'स्वर्गीय श्री'), ('स्वर्गीय श्रीमती', 'स्वर्गीय श्रीमती'), ('कु.', 'कु.'), ('डॉ.', 'डॉ.')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='daily_events/')),
                ('date_of_event', models.DateField()),
                ('is_show_home', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('birthday', 'Birthday'), ('punyatithi', 'Punyatithi'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
