# Generated by Django 4.2.23 on 2025-10-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_dailyevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyevent',
            options={'ordering': ['-event_date']},
        ),
        migrations.RenameField(
            model_name='dailyevent',
            old_name='is_show_home',
            new_name='show_on_home',
        ),
        migrations.RemoveField(
            model_name='dailyevent',
            name='date_of_event',
        ),
        migrations.RemoveField(
            model_name='dailyevent',
            name='reason',
        ),
        migrations.AddField(
            model_name='dailyevent',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailyevent',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyevent',
            name='salutation',
            field=models.CharField(choices=[('श्री', 'श्री'), ('श्रीमती', 'श्रीमती'), ('कुमार', 'कुमार'), ('कुमारी', 'कुमारी'), ('पूज्य', 'पूज्य'), ('स्व.', 'स्व.')], max_length=20),
        ),
    ]
