# Generated by Django 4.2.23 on 2025-10-13 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_dailyevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailyevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailyevent',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyevent',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('punyatithi', 'Punyatithi'), ('other', 'Other')], default='General', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyevent',
            name='salutation',
            field=models.CharField(choices=[('shri', 'श्री'), ('smt', 'श्रीमती'), ('kumar', 'कुमार'), ('kumari', 'कुमारी'), ('pandit', 'पंडित'), ('swami', 'स्वामी'), ('mata', 'माता'), ('pita', 'पिता')], max_length=20),
        ),
    ]
