# Generated by Django 4.2.23 on 2025-10-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_dailyevent_is_active_dailyevent_updated_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyevent',
            index=models.Index(fields=['-event_date'], name='booking_dai_event_d_b1e260_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyevent',
            index=models.Index(fields=['show_on_home'], name='booking_dai_show_on_517581_idx'),
        ),
    ]
