# Generated by Django 4.2.23 on 2025-10-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_dailyevent_booking_dai_event_d_b1e260_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyevent',
            name='booking_dai_event_d_b1e260_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyevent',
            name='booking_dai_show_on_517581_idx',
        ),
    ]
